# Generated by Django 3.1.7 on 2021-03-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210326_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='products.productvariant'),
        ),
    ]
