# Generated by Django 3.1.7 on 2021-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210327_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
