# Generated by Django 3.1.7 on 2021-03-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210329_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentimage',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='blog.blogcomment'),
        ),
    ]
