# Generated by Django 3.1.7 on 2021-03-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210329_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='images',
        ),
        migrations.DeleteModel(
            name='BlogCommentImage',
        ),
    ]
